/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.js to modify the generation of this file.


const components = new Map();


export default function componentFactory(componentName) {
  return components.get(componentName);
};
